version: '3.8'

networks:
  backend:
    external: true

services:
  node:
    image: node:lts
    volumes:
      - /work/projects/:/work/projects/
    ports:
      - 8000:8000
    networks:
      - backend
    tty: true