version: '3.8'

networks:
  backend:
    external: true

volumes:
  mysql57:
    name: mysql57
    driver: local
  mysql8:
    name: mysql8
    driver: local
  mariadb:
    name: mariadb
    driver: local

services:
  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql57:/var/lib/mysql
    ports:
      - 13306:3306
    networks:
      backend:
        aliases:
          - docker-mysql57
  
  mysql8:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql8:/var/lib/mysql
    ports:
      - 23306:3306
    networks:
      backend:
        aliases:
          - docker-mysql8
    
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 33306:3306
    networks:
      backend:
        aliases:
          - docker-mariadb
