version: '3.8'

networks:
  backend:
    external: true

services:
  php7.4-apache:
    build:
      context: ./php7.4-apache
      dockerfile: Dockerfile
      args:
        COMPOSER_VERSION: 2.0.8
    volumes:
      - /work/projects/:/work/projects/
    networks:
      backend:
        aliases:
          - docker-php7.4-apache

  php7.4-fpm:
    build:
      context: ./php7.4-fpm
      dockerfile: Dockerfile
      args:
        COMPOSER_VERSION: 2.0.8
    volumes:
      - /work/projects/:/work/projects/
    networks:
      backend:
        aliases:
          - docker-php7.4-fpm
  
  php8.0-fpm:
    build:
      context: ./php8.0-fpm
      dockerfile: Dockerfile
      args:
        COMPOSER_VERSION: 2.0.8
    volumes:
      - /work/projects/:/work/projects/
    networks:
      backend:
        aliases:
          - docker-php8.0-fpm
