version: '3.8'

networks:
  backend:
    external: true

volumes:
  redis:
    name: redis
    driver: local
  redis-manager-mysql:
    name: redis-manager-mysql
    driver: local

services:
  redis:
    image: redis
    volumes:
      - redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    networks:
      backend:
        aliases:
          - docker-redis
  
  redis-manager:
    image: reasonduan/redis-manager
    environment:
      DATASOURCE_DATABASE: redis_manager
      DATASOURCE_URL: jdbc:mysql://docker-redis-manager-mysql:3306/redis_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: 123456
    ports:
      - 8182:8182
    networks:
      - backend

  redis-manager-mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: redis_manager
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - redis-manager-mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - docker-redis-manager-mysql
